### ISSUE TITLE
E2E tests are broken

### ISSUE THREAD

**Issue by skozin** [lidofinance/lido-dao#170] opened 2020-11-23 03:37 UTC
The E2E tests were broken by the renaming and interfaces change in #153, e.g. see https://github.com/lidofinance/lido-dao/pull/153#pullrequestreview-536128939.

**Comment by ongrid** [comment] 2020-11-25 11:03
Not reproduced. Seems to be resolved in https://github.com/lidofinance/lido-dao/commit/02e3b58d05c114632e4e8dbc1ccd864da624d4ab

**Closed** 2020-11-25 23:18 UTC
Labels: invalid, wontfix
